// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoemtkelodkapnuvrdme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZW10a2Vsb2RrYXBudXZyZG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODk3OTgsImV4cCI6MjA2NjE2NTc5OH0.g5ax8FTCwmR7SmvbQkbYL-jL7K8dXCHYV0UZP0fB3A8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);